---
# Create the service account to be used for AWS providers
apiVersion: v1
kind: ServiceAccount
metadata:
  name: choclab-discovery
  namespace: crossplane
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/crossplane-assume-role

---
# DeploymentRuntimeConfig for composition functions
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: aws-discovery
spec:
  deploymentTemplate:
    spec:
      replicas: 1
      selector: {}
      template:
        spec:
          serviceAccountName: choclab-discovery
          containers:
          - name: package-runtime
            args:
            - --debug
            imagePullPolicy: Always

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: aws-discovery
  name: xfn-aws-provider-config-access
rules:
  - apiGroups:
      - aws.upbound.io
    resources:
      - providerconfigs
    verbs:
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: xfn-aws-provider-config-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: xfn-aws-provider-config-access
subjects:
  - kind: ServiceAccount
    name: choclab-discovery
    namespace: crossplane
